// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1775.Robot2016.subsystems;

import org.usfirst.frc1775.Robot2016.RobotMap;
import org.usfirst.frc1775.Robot2016.commands.*;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GrabbingArm extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController roller = RobotMap.grabbingArmRoller;
    private final SpeedController arm = RobotMap.grabbingArmArm;
    private final Solenoid ballRelease = RobotMap.grabbingArmBallRelease;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void rollerIn()
    {
    	roller.set(0.9);
    }
    
    public void ballRelease()
    {
    	ballRelease.set(true);
    }
    
    public void resetBallRelease()
    {
    	ballRelease.set(false);
    }
    
    public void rollerStop()
    {
    	roller.set(0);
    }
    
    public void rollerOut()
    {
    	roller.set(-0.9);
    }
    
    public void armUp()
    {
    	arm.set(0.3);
    }
    
    public void armStop()
    {
    	arm.set(0);
    }
    
    public void armDown()
    {
    	arm.set(-0.3);
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

